In [1]:
import pandas as pd 
import numpy as np

In [3]:
transaction=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\transactions.csv")

In [4]:
transaction.head(10)

,transaction_id,account_id,txn_date,txn_type,amount,channel,merchant_category
0,1,42369,2018-03-13,Deposit,1817.91,Online Banking,Salary Credit
1,2,53934,2022-03-05,Withdrawal,12855.96,Mobile App,ATM Withdrawal
2,3,53478,2022-05-29,Deposit,8278.61,UPI,Education
3,4,5270,2024-01-27,Interest Credit,18183.95,Branch,Dining
4,5,85021,2023-01-19,Fee Debit,19658.07,UPI,ATM Withdrawal
5,6,94147,2018-04-09,Transfer Out,5883.59,Mobile App,Shopping
6,7,59970,2022-01-09,Transfer In,1217.66,POS,Utilities
7,8,82104,2025-05-06,Deposit,31325.30,Mobile App,Entertainment
8,9,36132,2025-12-03,Withdrawal,11403.29,Mobile App,ATM Withdrawal
9,10,87038,2018-11-18,Transfer Out,2862.01,UPI,Entertainment

In [5]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 7 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     int64
 1   account_id         int64
 2   txn_date           str
 3   txn_type           str
 4   amount             float64
 5   channel            str
 6   merchant_category  str
dtypes: float64(1), int64(2), str(4)
memory usage: 106.8 MB

In [6]:
transaction.isnull().sum()

transaction_id       0
account_id           0
txn_date             0
txn_type             0
amount               0
channel              0
merchant_category    0
dtype: int64

In [ ]:
transaction['txn_date']=pd.to_datetime(transaction['txn_date'])
"""hi"""

In [8]:
transaction.tail()

,transaction_id,account_id,txn_date,txn_type,amount,channel,merchant_category
1999995,1999996,18977,2021-10-22,Transfer In,1363.05,Mobile App,Fuel
1999996,1999997,64322,2022-05-17,Withdrawal,4051.16,Mobile App,Education
1999997,1999998,90610,2018-05-09,Deposit,13755.15,Mobile App,Salary Credit
1999998,1999999,27682,2020-08-23,Deposit,12714.98,Mobile App,Fund Transfer
1999999,2000000,14670,2018-12-02,Transfer Out,11757.94,POS,Salary Credit

In [9]:
transaction.duplicated().sum()

np.int64(0)

In [7]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 7 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     int64
 1   account_id         int64
 2   txn_date           str
 3   txn_type           str
 4   amount             float64
 5   channel            str
 6   merchant_category  str
dtypes: float64(1), int64(2), str(4)
memory usage: 106.8 MB

In [8]:
loanpayment=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\loan_payments.csv")

In [9]:
loanpayment.head(10)

,payment_id,loan_id,payment_date,amount_paid,principal_component,interest_component,late_payment_flag
0,1,21070,2020-05-06,8144.05,5930.89,2213.16,0
1,2,17959,2011-09-23,6128.01,4406.78,1721.23,0
2,3,7239,2025-02-25,27946.17,25195.76,2750.41,0
3,4,9993,2015-10-04,5715.37,4082.41,1632.96,0
4,5,5487,2017-07-26,10119.72,9474.29,645.43,0
5,6,12643,2013-01-03,1734.55,1271.29,463.26,0
6,7,2454,2012-11-04,1923.11,1628.62,294.49,0
7,8,13712,2025-10-21,14567.03,10914.73,3652.30,0
8,9,8150,2015-11-30,5035.38,4324.19,711.19,0
9,10,10911,2012-12-27,12662.89,9129.15,3533.74,0

In [14]:
loanpayment.tail()

,payment_id,loan_id,payment_date,amount_paid,principal_component,interest_component,late_payment_flag
599995,599996,19615,2012-08-21,7237.32,6684.52,552.80,0
599996,599997,5909,2015-05-16,2896.48,2374.13,522.35,0
599997,599998,12025,2012-10-29,7390.46,5533.49,1856.97,0
599998,599999,801,2025-08-31,6346.48,5232.52,1113.96,0
599999,600000,19640,2016-08-17,17138.93,14965.51,2173.42,0

In [10]:
loanpayment.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   payment_id           600000 non-null  int64
 1   loan_id              600000 non-null  int64
 2   payment_date         600000 non-null  str
 3   amount_paid          600000 non-null  float64
 4   principal_component  600000 non-null  float64
 5   interest_component   600000 non-null  float64
 6   late_payment_flag    600000 non-null  int64
dtypes: float64(3), int64(3), str(1)
memory usage: 32.0 MB

In [28]:
loanpayment['payment_date']=pd.to_datetime(loanpayment['payment_date'])

In [11]:
loanpayment.describe()

,payment_id,loan_id,amount_paid,principal_component,interest_component,late_payment_flag
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000
mean,300000.500000,11003.130957,10397.459895,8487.303101,1910.156795,0.120063
std,173205.225094,6343.123591,9856.840472,7988.881191,2148.616537,0.325036
min,1.000000,1.000000,526.270000,500.030000,25.400000,0.000000
25%,150000.750000,5516.000000,3409.955000,2798.770000,505.977500,0.000000
50%,300000.500000,10997.000000,7361.825000,6032.060000,1177.950000,0.000000
75%,450000.250000,16495.000000,14138.020000,11571.875000,2507.290000,0.000000
max,600000.000000,22000.000000,147281.590000,110436.890000,36844.700000,1.000000

In [30]:
loanpayment["payment_year"] =loanpayment["payment_date"].dt.year
loanpayment["payment_month"] = loanpayment["payment_date"].dt.month

In [14]:
loanpayment.columns

Index(['payment_id', 'loan_id', 'payment_date', 'amount_paid',
       'principal_component', 'interest_component', 'late_payment_flag'],
      dtype='str')

In [15]:
transaction.columns

Index(['transaction_id', 'account_id', 'txn_date', 'txn_type', 'amount',
       'channel', 'merchant_category'],
      dtype='str')

In [16]:
loan=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\loans.csv")

In [28]:
loan.head()

,loan_id,customer_id,branch_id,loan_type,loan_amount,interest_rate,term_months,start_date,status
0,1,48019,129,Auto Loan,310670.27,9.54,60,2020-06-16,Active
1,2,47355,38,Education Loan,599321.65,16.20,12,2016-06-05,Active
2,3,30661,29,Gold Loan,135377.18,10.25,24,2012-07-03,Active
3,4,1755,66,Education Loan,20798.63,8.37,180,2013-01-27,Defaulted
4,5,18763,23,Education Loan,84367.97,8.97,60,2017-02-11,Active

In [29]:
loan.tail()

,loan_id,customer_id,branch_id,loan_type,loan_amount,interest_rate,term_months,start_date,status
21995,21996,53987,106,Business Loan,305636.98,9.02,84,2020-10-08,Active
21996,21997,13161,117,Personal Loan,1215540.98,14.12,36,2015-01-07,Defaulted
21997,21998,52751,41,Business Loan,29847.40,11.33,36,2016-04-21,Active
21998,21999,58299,7,Home Loan,263288.12,11.07,180,2025-03-10,Active
21999,22000,17714,46,Gold Loan,218497.08,7.28,24,2021-06-06,Closed

In [17]:
loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   loan_id        22000 non-null  int64
 1   customer_id    22000 non-null  int64
 2   branch_id      22000 non-null  int64
 3   loan_type      22000 non-null  str
 4   loan_amount    22000 non-null  float64
 5   interest_rate  22000 non-null  float64
 6   term_months    22000 non-null  int64
 7   start_date     22000 non-null  str
 8   status         22000 non-null  str
dtypes: float64(2), int64(4), str(3)
memory usage: 1.5 MB

In [18]:
loan['start_date ']=pd.to_datetime(loan['start_date'])

In [19]:
loan.columns

Index(['loan_id', 'customer_id', 'branch_id', 'loan_type', 'loan_amount',
       'interest_rate', 'term_months', 'start_date', 'status', 'start_date '],
      dtype='str')

In [20]:
loan.columns

Index(['loan_id', 'customer_id', 'branch_id', 'loan_type', 'loan_amount',
       'interest_rate', 'term_months', 'start_date', 'status', 'start_date '],
      dtype='str')

In [21]:
transaction.columns

Index(['transaction_id', 'account_id', 'txn_date', 'txn_type', 'amount',
       'channel', 'merchant_category'],
      dtype='str')

In [23]:
transaction['txn_date'] = pd.to_datetime(transaction['txn_date'])

In [24]:
transaction['transaction_year'] = transaction['txn_date'].dt.year

In [25]:
transaction.columns

Index(['transaction_id', 'account_id', 'txn_date', 'txn_type', 'amount',
       'channel', 'merchant_category', 'transaction_year'],
      dtype='str')

In [26]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     int64
 1   account_id         int64
 2   txn_date           datetime64[us]
 3   txn_type           str
 4   amount             float64
 5   channel            str
 6   merchant_category  str
 7   transaction_year   int32
dtypes: datetime64[us](1), float64(1), int32(1), int64(2), str(3)
memory usage: 114.4 MB

In [31]:
loanpayment.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   payment_id           600000 non-null  int64
 1   loan_id              600000 non-null  int64
 2   payment_date         600000 non-null  datetime64[us]
 3   amount_paid          600000 non-null  float64
 4   principal_component  600000 non-null  float64
 5   interest_component   600000 non-null  float64
 6   late_payment_flag    600000 non-null  int64
 7   payment_year         600000 non-null  int32
 8   payment_month        600000 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(2), int64(3)
memory usage: 36.6 MB

In [32]:
loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   loan_id        22000 non-null  int64
 1   customer_id    22000 non-null  int64
 2   branch_id      22000 non-null  int64
 3   loan_type      22000 non-null  str
 4   loan_amount    22000 non-null  float64
 5   interest_rate  22000 non-null  float64
 6   term_months    22000 non-null  int64
 7   start_date     22000 non-null  str
 8   status         22000 non-null  str
 9   start_date     22000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(4), str(3)
memory usage: 1.7 MB

In [33]:
supportticket=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\support_tickets.csv")

In [34]:
supportticket.head()

,ticket_id,customer_id,issue_type,date_opened,date_resolved,status,satisfaction_score
0,1,16045,App Login Issue,2024-08-04,2024-08-19,Resolved,5
1,2,8088,App Login Issue,2021-07-13,2021-07-27,Resolved,1
2,3,47568,Card Blocked,2021-06-23,2021-07-08,Resolved,3
3,4,36826,KYC Update,2022-12-04,2022-12-18,Resolved,4
4,5,7289,Interest Query,2023-06-22,2023-07-11,Open,5

In [35]:
supportticket['date_opened'] = pd.to_datetime(supportticket['date_opened'])

In [36]:
supportticket.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           25000 non-null  int64
 1   customer_id         25000 non-null  int64
 2   issue_type          25000 non-null  str
 3   date_opened         25000 non-null  datetime64[us]
 4   date_resolved       25000 non-null  str
 5   status              25000 non-null  str
 6   satisfaction_score  25000 non-null  int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 1.3 MB

In [37]:
cardtransaction=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\card_transactions.csv")

In [38]:
cardtransaction.head()

   card_txn_id  card_id    txn_date merchant_category   amount  is_fraud
0            1    52505  2025-01-28         Education  2162.41         0
1            2    12716  2022-08-26         Education  2236.55         0
2            3    49060  2019-10-07            Travel  1184.59         0
3            4    18295  2019-03-07            Travel   124.79         0
4            5    54342  2026-03-26         Insurance   546.10         0

In [39]:
cardtransaction['txn_date'] = pd.to_datetime(cardtransaction['txn_date'])

In [40]:
cardtransaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   card_txn_id        int64
 1   card_id            int64
 2   txn_date           datetime64[us]
 3   merchant_category  str
 4   amount             float64
 5   is_fraud           int64
dtypes: datetime64[us](1), float64(1), int64(3), str(1)
memory usage: 137.3 MB

In [41]:
cardtransaction.isnull().sum()

card_txn_id          0
card_id              0
txn_date             0
merchant_category    0
amount               0
is_fraud             0
dtype: int64

In [43]:
cardtransaction.duplicated().sum()

np.int64(0)

In [44]:
card=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\cards.csv")

In [45]:
card.head()

,card_id,customer_id,account_id,card_type,issue_date,expiry_date,credit_limit,status
0,1,34846,75950,Credit - Gold,2018-12-05,2023-12-04,0,Active
1,2,50151,55880,Credit - Classic,2016-05-19,2021-05-18,0,Active
2,3,11246,86152,Credit - Gold,2023-08-30,2028-08-28,50000,Active
3,4,23866,10907,Credit - Classic,2018-07-24,2023-07-23,0,Active
4,5,14097,22455,Credit - Classic,2023-08-16,2028-08-14,50000,Active

In [46]:
card.info()

<class 'pandas.DataFrame'>
RangeIndex: 65000 entries, 0 to 64999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   card_id       65000 non-null  int64
 1   customer_id   65000 non-null  int64
 2   account_id    65000 non-null  int64
 3   card_type     65000 non-null  str
 4   issue_date    65000 non-null  str
 5   expiry_date   65000 non-null  str
 6   credit_limit  65000 non-null  int64
 7   status        65000 non-null  str
dtypes: int64(4), str(4)
memory usage: 4.0 MB

In [48]:
card['issue_date'] = pd.to_datetime(card['issue_date'])
card['expiry_date'] = pd.to_datetime(card['expiry_date'])

In [49]:
card.info()

<class 'pandas.DataFrame'>
RangeIndex: 65000 entries, 0 to 64999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   card_id       65000 non-null  int64
 1   customer_id   65000 non-null  int64
 2   account_id    65000 non-null  int64
 3   card_type     65000 non-null  str
 4   issue_date    65000 non-null  datetime64[us]
 5   expiry_date   65000 non-null  datetime64[us]
 6   credit_limit  65000 non-null  int64
 7   status        65000 non-null  str
dtypes: datetime64[us](2), int64(4), str(2)
memory usage: 4.0 MB

In [50]:
customer=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\customers.csv")

In [51]:
customer.head()

,customer_id,name,gender,date_of_birth,city,state,phone,email,occupation,annual_income,join_date,credit_score
0,1,Pooja Garcia,Male,1987-12-11,Ahmedabad,Gujarat,9562078082,customer0@mailbank.com,Retired,200025,2018-02-23,690
1,2,Anjali Kapoor,Female,1965-12-18,Lucknow,Uttar Pradesh,9599825073,customer1@mailbank.com,Salaried - Government,1865003,2020-11-08,672
2,3,James Smith,Female,1979-03-12,Chandigarh,Punjab,9572599111,customer2@mailbank.com,Salaried - Government,1709141,2007-04-22,422
3,4,Susan Joshi,Male,1996-11-07,Nagpur,Maharashtra,9364883923,customer3@mailbank.com,Salaried - Private,1917060,2009-01-18,498
4,5,Kiran Mehta,Male,1952-02-17,Lucknow,Uttar Pradesh,9753361420,customer4@mailbank.com,Freelancer,2398864,2019-01-21,690

In [56]:
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    60000 non-null  int64
 1   name           60000 non-null  str
 2   gender         60000 non-null  str
 3   date_of_birth  60000 non-null  datetime64[us]
 4   city           60000 non-null  str
 5   state          60000 non-null  str
 6   phone          60000 non-null  int64
 7   email          60000 non-null  str
 8   occupation     60000 non-null  str
 9   annual_income  60000 non-null  int64
 10  join_date      60000 non-null  datetime64[us]
 11  credit_score   60000 non-null  int64
dtypes: datetime64[us](2), int64(4), str(6)
memory usage: 5.5 MB

In [54]:
customer['date_of_birth'] = pd.to_datetime(customer['date_of_birth'])
customer['join_date'] = pd.to_datetime(customer['join_date'])

In [55]:
customer.isnull().sum()

customer_id      0
name             0
gender           0
date_of_birth    0
city             0
state            0
phone            0
email            0
occupation       0
annual_income    0
join_date        0
credit_score     0
dtype: int64

In [57]:
customer.tail()

,customer_id,name,gender,date_of_birth,city,state,phone,email,occupation,annual_income,join_date,credit_score
59995,59996,Priya Desai,Female,1988-08-02,Ahmedabad,Gujarat,9307135414,customer59995@mailbank.com,Self Employed,530569,2017-07-15,836
59996,59997,Susan Verma,Male,1985-10-26,Chennai,Tamil Nadu,9172933389,customer59996@mailbank.com,Freelancer,824262,2024-04-17,801
59997,59998,Meera Rodriguez,Male,1965-05-05,Nagpur,Maharashtra,9515112666,customer59997@mailbank.com,Salaried - Private,1224910,2008-07-12,754
59998,59999,Jennifer Desai,Male,2003-11-08,Jaipur,Rajasthan,9956126472,customer59998@mailbank.com,Business Owner,2906687,2006-11-12,638
59999,60000,Joseph Joshi,Male,1978-07-21,Jaipur,Rajasthan,9287644121,customer59999@mailbank.com,Business Owner,2734414,2024-10-09,609

In [58]:
employee=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\employees.csv")

In [59]:
employee.head()

,employee_id,name,branch_id,role,hire_date,salary
0,1,Richard Rodriguez,30,Customer Service,2016-11-09,62479
1,2,Robert Rodriguez,136,Relationship Manager,2010-08-04,50855
2,3,Arjun Rodriguez,35,Customer Service,2020-02-12,94948
3,4,Arjun Singh,146,Loan Officer,2022-02-11,40756
4,5,Robert Joshi,29,Customer Service,2010-05-09,155016

In [60]:
employee.tail()

,employee_id,name,branch_id,role,hire_date,salary
1795,1796,Jennifer Smith,65,Loan Officer,2023-07-05,59331
1796,1797,Suresh Desai,47,Relationship Manager,2016-07-24,142320
1797,1798,Barbara Chopra,123,Relationship Manager,2011-02-14,59085
1798,1799,Sanjay Kumar,62,Teller,2015-12-09,50724
1799,1800,Jennifer Menon,49,Teller,2022-02-24,30049

In [61]:
employee.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  1800 non-null   int64
 1   name         1800 non-null   str
 2   branch_id    1800 non-null   int64
 3   role         1800 non-null   str
 4   hire_date    1800 non-null   str
 5   salary       1800 non-null   int64
dtypes: int64(3), str(3)
memory usage: 84.5 KB

In [64]:
employee['hire_date'] = pd.to_datetime(employee['hire_date'])

In [66]:
employee.describe()

       employee_id    branch_id            hire_date         salary
count   1800.00000  1800.000000                 1800    1800.000000
mean     900.50000    74.823333  2012-07-16 23:46:24  103739.217222
min        1.00000     1.000000  2000-01-03 00:00:00   28063.000000
25%      450.75000    39.000000  2006-07-22 00:00:00   65276.000000
50%      900.50000    75.000000  2012-02-02 12:00:00  104710.000000
75%     1350.25000   113.000000  2018-09-15 12:00:00  141937.000000
max     1800.00000   150.000000  2025-05-31 00:00:00  179802.000000
std      519.75956    43.086555                  NaN   43991.296888

In [67]:
account=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\accounts.csv")

In [68]:
account.head()

,account_id,customer_id,branch_id,account_type,balance,open_date,status
0,1,11749,141,Current,95902.00,2019-10-20,Active
1,2,47716,43,Current,13261.61,2026-02-03,Active
2,3,56143,90,Savings,26495.92,2020-10-19,Active
3,4,29193,113,Salary,74682.72,2012-02-22,Active
4,5,49907,28,Current,40419.01,2007-01-03,Active

In [69]:
account['open_date'] = pd.to_datetime(account['open_date'])

In [70]:
account.info()

<class 'pandas.DataFrame'>
RangeIndex: 95000 entries, 0 to 94999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    95000 non-null  int64
 1   customer_id   95000 non-null  int64
 2   branch_id     95000 non-null  int64
 3   account_type  95000 non-null  str
 4   balance       95000 non-null  float64
 5   open_date     95000 non-null  datetime64[us]
 6   status        95000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(3), str(2)
memory usage: 5.1 MB

In [71]:
branch=pd.read_csv(r"C:\Users\Prime\Downloads\archive (15)\branches.csv")

In [72]:
branch.head()

,branch_id,branch_name,city,state,opened_date,ifsc_code
0,1,Pune Branch 1,Pune,Maharashtra,2016-05-23,BNK0000000
1,2,Bhopal Branch 2,Bhopal,Madhya Pradesh,2002-01-13,BNK0000001
2,3,Lucknow Branch 3,Lucknow,Uttar Pradesh,2017-12-10,BNK0000002
3,4,Kolkata Branch 4,Kolkata,West Bengal,2002-05-04,BNK0000003
4,5,Kolkata Branch 5,Kolkata,West Bengal,2005-11-09,BNK0000004

In [73]:
branch['opened_date'] = pd.to_datetime(branch['opened_date'])

In [74]:
branch.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    150 non-null    int64
 1   branch_name  150 non-null    str
 2   city         150 non-null    str
 3   state        150 non-null    str
 4   opened_date  150 non-null    datetime64[us]
 5   ifsc_code    150 non-null    str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 7.2 KB

In [75]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     int64
 1   account_id         int64
 2   txn_date           datetime64[us]
 3   txn_type           str
 4   amount             float64
 5   channel            str
 6   merchant_category  str
 7   transaction_year   int32
dtypes: datetime64[us](1), float64(1), int32(1), int64(2), str(3)
memory usage: 114.4 MB

In [76]:
loanpayment.info()

<class 'pandas.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   payment_id           600000 non-null  int64
 1   loan_id              600000 non-null  int64
 2   payment_date         600000 non-null  datetime64[us]
 3   amount_paid          600000 non-null  float64
 4   principal_component  600000 non-null  float64
 5   interest_component   600000 non-null  float64
 6   late_payment_flag    600000 non-null  int64
 7   payment_year         600000 non-null  int32
 8   payment_month        600000 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(2), int64(3)
memory usage: 36.6 MB

In [77]:
loan.info()

<class 'pandas.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   loan_id        22000 non-null  int64
 1   customer_id    22000 non-null  int64
 2   branch_id      22000 non-null  int64
 3   loan_type      22000 non-null  str
 4   loan_amount    22000 non-null  float64
 5   interest_rate  22000 non-null  float64
 6   term_months    22000 non-null  int64
 7   start_date     22000 non-null  str
 8   status         22000 non-null  str
 9   start_date     22000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(4), str(3)
memory usage: 1.7 MB

In [78]:
cardtransaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   card_txn_id        int64
 1   card_id            int64
 2   txn_date           datetime64[us]
 3   merchant_category  str
 4   amount             float64
 5   is_fraud           int64
dtypes: datetime64[us](1), float64(1), int64(3), str(1)
memory usage: 137.3 MB

In [79]:
card.info()

<class 'pandas.DataFrame'>
RangeIndex: 65000 entries, 0 to 64999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   card_id       65000 non-null  int64
 1   customer_id   65000 non-null  int64
 2   account_id    65000 non-null  int64
 3   card_type     65000 non-null  str
 4   issue_date    65000 non-null  datetime64[us]
 5   expiry_date   65000 non-null  datetime64[us]
 6   credit_limit  65000 non-null  int64
 7   status        65000 non-null  str
dtypes: datetime64[us](2), int64(4), str(2)
memory usage: 4.0 MB

In [80]:
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    60000 non-null  int64
 1   name           60000 non-null  str
 2   gender         60000 non-null  str
 3   date_of_birth  60000 non-null  datetime64[us]
 4   city           60000 non-null  str
 5   state          60000 non-null  str
 6   phone          60000 non-null  int64
 7   email          60000 non-null  str
 8   occupation     60000 non-null  str
 9   annual_income  60000 non-null  int64
 10  join_date      60000 non-null  datetime64[us]
 11  credit_score   60000 non-null  int64
dtypes: datetime64[us](2), int64(4), str(6)
memory usage: 5.5 MB

In [81]:
supportticket.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           25000 non-null  int64
 1   customer_id         25000 non-null  int64
 2   issue_type          25000 non-null  str
 3   date_opened         25000 non-null  datetime64[us]
 4   date_resolved       25000 non-null  str
 5   status              25000 non-null  str
 6   satisfaction_score  25000 non-null  int64
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 1.3 MB

In [82]:
employee.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  1800 non-null   int64
 1   name         1800 non-null   str
 2   branch_id    1800 non-null   int64
 3   role         1800 non-null   str
 4   hire_date    1800 non-null   datetime64[us]
 5   salary       1800 non-null   int64
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 84.5 KB

In [83]:
account.info()

<class 'pandas.DataFrame'>
RangeIndex: 95000 entries, 0 to 94999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    95000 non-null  int64
 1   customer_id   95000 non-null  int64
 2   branch_id     95000 non-null  int64
 3   account_type  95000 non-null  str
 4   balance       95000 non-null  float64
 5   open_date     95000 non-null  datetime64[us]
 6   status        95000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(3), str(2)
memory usage: 5.1 MB

In [84]:
branch.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    150 non-null    int64
 1   branch_name  150 non-null    str
 2   city         150 non-null    str
 3   state        150 non-null    str
 4   opened_date  150 non-null    datetime64[us]
 5   ifsc_code    150 non-null    str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 7.2 KB

In [86]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

username = "root"
password = "Shankru@123"
host = "localhost"
port = 3306
database = "bankingdb"

connection_url = URL.create(
    drivername="mysql+pymysql",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(connection_url)

In [ ]:
customer.to_sql("customer", engine, if_exists="replace", index=False)

branch.to_sql("branch", engine, if_exists="replace", index=False)

employee.to_sql("employee", engine, if_exists="replace", index=False)

account.to_sql("account", engine, if_exists="replace", index=False)

transaction.to_sql("transaction", engine, if_exists="replace", index=False)

card.to_sql("card", engine, if_exists="replace", index=False)

cardtransaction.to_sql("cardtransaction", engine, if_exists="replace", index=False)

loan.to_sql("loan", engine, if_exists="replace", index=False)

loanpayment.to_sql("loanpayment", engine, if_exists="replace", index=False)

supportticket.to_sql("supportticket", engine, if_exists="replace", index=False)

In [87]:
customer.to_sql("customer", engine, if_exists="replace", index=False)

60000

In [88]:
branch.to_sql("branch", engine, if_exists="replace", index=False)

150

In [89]:
employee.to_sql("employee", engine, if_exists="replace", index=False)

1800

In [90]:
account.to_sql("account", engine, if_exists="replace", index=False)

95000

In [91]:
transaction.to_sql("transaction", engine, if_exists="replace", index=False)

2000000

In [92]:
card.to_sql("card", engine, if_exists="replace", index=False)

65000

In [93]:
cardtransaction.to_sql("cardtransaction", engine, if_exists="replace", index=False)

3000000

In [98]:
loan.to_sql("loan", engine, if_exists="replace", index=False)

22000

In [95]:
loan = loan.drop(columns=['start_date '])

In [96]:
loan.columns.tolist()

['loan_id',
 'customer_id',
 'branch_id',
 'loan_type',
 'loan_amount',
 'interest_rate',
 'term_months',
 'start_date',
 'status']

In [97]:
loan.columns

Index(['loan_id', 'customer_id', 'branch_id', 'loan_type', 'loan_amount',
       'interest_rate', 'term_months', 'start_date', 'status'],
      dtype='str')

In [99]:
loanpayment.to_sql("loanpayment", engine, if_exists="replace", index=False)

600000

In [100]:
supportticket.to_sql("supportticket", engine, if_exists="replace", index=False)

25000